[target.wasm32-unknown-unknown]
rustflags = ["-C", "link-arg=-s"]

# instead of creating a new profile, this might be helpful:
# https://doc.rust-lang.org/cargo/reference/profiles.html#overrides
[profile.wasm-release]
inherits = "release"   # base this on the default release profile
codegen-units = 1      # generate a single blob of machine/Wasm instructions
opt-level = "z"        # optimize for code size
lto = true             # compile at link time
debug = false          # no debug symbols/checks
panic = "abort"        # usually unwind, but that's extra overhead
overflow-checks = true # enable safety checks for arithmetic operations

[alias]
wasm = "rustc --target wasm32-unknown-unknown --profile wasm-release"
mb-nft-v1 = "wasm -p mb-nft-v1 -- --emit link=wasm/mb-nft-v1.wasm"
mb-nft-v2 = "wasm -p mb-nft-v2 -- --emit link=wasm/mb-nft-v2.wasm"
factory-v1 = "wasm -p mb-factory-v1 -- --emit link=wasm/factory-v1.wasm"
factory-v2 = "wasm -p mb-factory-v2 -- --emit link=wasm/factory-v2.wasm"
legacy-market = "wasm -p mb-legacy-market -- --emit link=wasm/legacy-market.wasm"
interop-market = "wasm -p mb-interop-market -- --emit link=wasm/interop-market.wasm"
lint = "clippy -- -D warnings"
